### PR TITLE
Add Bryson Manager photo

### PR DESCRIPTION
**Pull request by JesseNoseworthy**
Adding `manager.jpg`:

manager

### CODE REVIEW

**Review by jmreid — COMMENTED** [review]
Can we compress this image down a bit?

**Review by brysongilbert — CHANGES_REQUESTED** [review]
i feel attacked

**Comment by JesseNoseworthy** [comment]
> Can we compress this image down a bit?



For sure! Handled in https://github.com/mattdrose/placebryson/pull/3/commits/f972e00745277e27625ea9a190702c5e330ffe4a

**Review by mattdrose — APPROVED** [review]

**Comment by stevebosworth** [comment]
I think @brysongilbert wants to speak to the manager

**Pull request merged**
